// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriElemental.App.Persistencia;

namespace NutriElemental.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211002220941_Entidades")]
    partial class Entidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NutriElemental.App.Dominio.AntecedenteFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Antecedente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("AntecedentesFamiliares");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.AntecedentePersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Antecedente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("AntecedentesPersonales");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.RegistroNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Actividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Animo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Hora_Registro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lugar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("RegistroNutricionales");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.SugerenciaNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Sugerencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("SugerenciasNutricionales");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Coach", b =>
                {
                    b.HasBaseType("NutriElemental.App.Dominio.Persona");

                    b.Property<int>("HorasLaborales")
                        .HasColumnType("int");

                    b.Property<string>("TarjetaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Nutricionista", b =>
                {
                    b.HasBaseType("NutriElemental.App.Dominio.Persona");

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroRethus")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Nutricionista");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Paciente", b =>
                {
                    b.HasBaseType("NutriElemental.App.Dominio.Persona");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.Property<int?>("NutricionistaId")
                        .HasColumnType("int");

                    b.HasIndex("CoachId");

                    b.HasIndex("NutricionistaId");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.AntecedenteFamiliar", b =>
                {
                    b.HasOne("NutriElemental.App.Dominio.Historia", null)
                        .WithMany("AntecedentesFamiliares")
                        .HasForeignKey("HistoriaId");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.AntecedentePersonal", b =>
                {
                    b.HasOne("NutriElemental.App.Dominio.Historia", null)
                        .WithMany("AntecedentesPersonales")
                        .HasForeignKey("HistoriaId");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Historia", b =>
                {
                    b.HasOne("NutriElemental.App.Dominio.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.RegistroNutricional", b =>
                {
                    b.HasOne("NutriElemental.App.Dominio.Paciente", null)
                        .WithMany("RegistroNutricional")
                        .HasForeignKey("PacienteId");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.SugerenciaNutricional", b =>
                {
                    b.HasOne("NutriElemental.App.Dominio.Historia", null)
                        .WithMany("SugerenciaNutricional")
                        .HasForeignKey("HistoriaId");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Paciente", b =>
                {
                    b.HasOne("NutriElemental.App.Dominio.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId");

                    b.HasOne("NutriElemental.App.Dominio.Nutricionista", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("NutricionistaId");

                    b.Navigation("Coach");

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Historia", b =>
                {
                    b.Navigation("AntecedentesFamiliares");

                    b.Navigation("AntecedentesPersonales");

                    b.Navigation("SugerenciaNutricional");
                });

            modelBuilder.Entity("NutriElemental.App.Dominio.Paciente", b =>
                {
                    b.Navigation("RegistroNutricional");
                });
#pragma warning restore 612, 618
        }
    }
}
